
import './globals.css'
import {UiLayout} from '@/components/ui/ui-layout'
import {ReactQueryProvider} from './react-query-provider'
import {Raleway} from "next/font/google"
import { useContext, createContext } from 'react'

import { WalletModalProvider } from '@solana/wallet-adapter-react-ui';
import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';

import {
    PhantomWalletAdapter,
    SolflareWalletAdapter,
} from '@solana/wallet-adapter-wallets';
import { clusterApiUrl } from '@solana/web3.js';
import WalletContextProvider from './contexts/WalletContextProvider'


const raleway = Raleway({
  subsets: ["latin"], // Loads only Latin characters
  weight: ["400", "700"], // Add specific weights
  display: "swap",
});


export const metadata = {
  title: 'Scaffold',
  description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const endpoint = clusterApiUrl('devnet'); // or 'mainnet-beta'

    const wallets = [
        new PhantomWalletAdapter(),
        new SolflareWalletAdapter(),
    ];
  return (
    <html lang="en">
      <head />
      <body className={raleway.className}>
        <WalletContextProvider>
          <ReactQueryProvider>
            <UiLayout links={links}>{children}</UiLayout>
          </ReactQueryProvider>
        </WalletContextProvider>
      </body>
    </html>
  );
}
